# Generated by Django 2.1 on 2021-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fert_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
