# Generated by Django 2.1 on 2021-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertmodel',
            name='fert_name',
        ),
        migrations.AddField(
            model_name='fertmodel',
            name='alumb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertmodel',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
