# Generated by Django 2.1 on 2021-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210204_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FertModel',
            new_name='Movie',
        ),
    ]
