# Generated by Django 2.1 on 2021-02-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210204_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='alumb',
            new_name='album',
        ),
    ]
