# Generated by Django 2.1 on 2021-02-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210205_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
